/* AI / ML & GenAI career track — concept questions (interview style). Format: [topic, question, [options], answerIndex, explanation] */
(function (root) {
  const B = (root.EP_BANK = root.EP_BANK || {});

  B.mlfund = [
    ['Bias–Variance', 'A model scores 99% on training data but 70% on validation data. This most likely indicates:', ['High bias (underfitting)', 'High variance (overfitting)', 'Data leakage into validation', 'A learning rate that is too low'], 1, 'Large train–validation gap = high variance. Remedies: more data, regularisation, simpler model, early stopping, augmentation.'],
    ['Bias–Variance', 'Both training and validation accuracy are low and close to each other. The best next step is usually to:', ['Add dropout', 'Collect a smaller dataset', 'Use a more expressive model or better features', 'Increase L2 regularisation'], 2, 'That is underfitting (high bias): add capacity or better features, and reduce regularisation.'],
    ['Regularisation', 'Which regularisation tends to drive some weights exactly to zero (feature selection)?', ['L2 (Ridge)', 'L1 (Lasso)', 'Dropout', 'Batch normalisation'], 1, 'L1\'s penalty |w| has a corner at 0, producing sparse solutions. L2 shrinks weights smoothly towards (not to) zero.'],
    ['Evaluation Metrics', 'For fraud detection where frauds are 0.5% of transactions, which metric is LEAST informative on its own?', ['Recall', 'Precision', 'Accuracy', 'PR-AUC'], 2, 'Predicting "never fraud" already gives 99.5% accuracy. Use precision, recall, F1 or PR-AUC for imbalanced data.'],
    ['Evaluation Metrics', 'In cancer screening you most want to avoid missing actual cancers. Which metric should you prioritise?', ['Precision', 'Recall (sensitivity)', 'Specificity', 'Accuracy'], 1, 'Missed cancers are false negatives; recall = TP / (TP + FN) measures how many positives you catch.'],
    ['Evaluation Metrics', 'ROC-AUC of 0.5 means the classifier:', ['Is perfect', 'Ranks positives above negatives no better than random', 'Always predicts the positive class', 'Has 50% accuracy'], 1, 'AUC is the probability a random positive is scored above a random negative; 0.5 = chance.'],
    ['Validation', 'Why use k-fold cross-validation instead of one train/validation split?', ['It trains faster', 'It gives a more reliable estimate of generalisation by averaging over several splits', 'It removes the need for a test set', 'It prevents overfitting during training'], 1, 'Every sample is used for validation once, reducing variance of the estimate. You still keep a final held-out test set.'],
    ['Validation', 'You scale features using the mean and std of the whole dataset before splitting into train/test. This is a problem because:', ['Scaling is unnecessary for most models', 'It leaks information from the test set into training', 'It makes training slower', 'Standard scaling only works on images'], 1, 'Fit preprocessing on the training split only, then apply it to validation/test (e.g., inside a scikit-learn Pipeline).'],
    ['Validation', 'For forecasting next month\'s sales, the right validation strategy is:', ['Random k-fold', 'Stratified k-fold', 'Time-based split (train on past, validate on future)', 'Leave-one-out on shuffled data'], 2, 'Shuffling time series leaks the future into training. Use forward-chaining / time-series splits.'],
    ['Algorithms', 'Logistic regression outputs:', ['A class label only', 'A probability via the sigmoid of a linear function', 'A distance to the nearest centroid', 'A decision tree'], 1, 'p = σ(wᵀx + b); threshold (e.g., 0.5) gives the class. Trained by minimising log loss (cross-entropy).'],
    ['Algorithms', 'Random Forest reduces variance compared to a single decision tree mainly by:', ['Boosting — each tree fixes previous errors', 'Bagging and random feature subsets, then averaging', 'Pruning every tree to depth 1', 'Using gradient descent'], 1, 'Bootstrap samples + random feature selection decorrelate trees; averaging reduces variance. Boosting (XGBoost, LightGBM) is sequential.'],
    ['Algorithms', 'Gradient boosting (e.g., XGBoost) builds each new tree to fit:', ['A random bootstrap sample', 'The residual errors (negative gradient) of the current ensemble', 'The test set', 'Only the most important feature'], 1, 'Each weak learner fits the gradient of the loss w.r.t. current predictions, scaled by a learning rate.'],
    ['Algorithms', 'k-means clustering requires you to choose:', ['The number of clusters k', 'The labels of each point', 'A learning rate', 'The depth of the tree'], 0, 'k-means is unsupervised; k is chosen with the elbow method, silhouette score or domain knowledge. It is sensitive to scaling and initialisation.'],
    ['Algorithms', 'Which algorithm is most sensitive to feature scaling?', ['Decision tree', 'Random forest', 'k-nearest neighbours', 'Naive Bayes (categorical)'], 2, 'Distance-based methods (k-NN, k-means, SVM with RBF) and gradient-based models need scaled features; trees split on thresholds and don\'t.'],
    ['Dimensionality Reduction', 'PCA finds directions that:', ['Maximise class separation', 'Maximise variance of the projected data', 'Minimise the number of samples', 'Are always the original features'], 1, 'Principal components are orthogonal directions of maximum variance (eigenvectors of the covariance matrix). LDA maximises class separation.'],
    ['Feature Engineering', 'One-hot encoding a "city" feature with 50,000 unique values is problematic mainly because:', ['It loses information', 'It creates a huge sparse feature space; target/frequency encoding or embeddings scale better', 'Trees cannot use it', 'It changes the labels'], 1, 'High-cardinality categoricals blow up dimensionality. Alternatives: target encoding (with care for leakage), hashing, learned embeddings.'],
    ['Optimisation', 'If training loss oscillates wildly and diverges, the first thing to try is:', ['Increase the learning rate', 'Decrease the learning rate', 'Remove the validation set', 'Add more layers'], 1, 'Too-large steps overshoot minima. Lower the LR, use a scheduler/warm-up, or gradient clipping.'],
    ['Statistics', 'A p-value of 0.03 in an A/B test means:', ['There is a 3% chance the new version is worse', 'If there were truly no difference, results at least this extreme would occur 3% of the time', 'The effect size is 3%', 'The test has 97% power'], 1, 'It is P(data this extreme | null is true), not the probability the null is true.'],
  ];

  B.dl = [
    ['Training Deep Nets', 'Backpropagation computes:', ['The optimal learning rate', 'Gradients of the loss w.r.t. every parameter using the chain rule', 'The forward pass only', 'The number of layers needed'], 1, 'Backprop applies the chain rule backwards through the computation graph; an optimiser (SGD, Adam) then uses those gradients.'],
    ['Training Deep Nets', 'Vanishing gradients in deep networks are mitigated by:', ['Sigmoid activations everywhere', 'ReLU-family activations, residual connections and normalisation', 'Removing the bias terms', 'Using a larger batch only'], 1, 'Saturating sigmoids/tanh shrink gradients. ReLU, skip connections (ResNets, Transformers) and careful init/normalisation keep them healthy.'],
    ['Training Deep Nets', 'Dropout during training:', ['Removes neurons permanently', 'Randomly zeroes activations so the network cannot rely on any single unit', 'Speeds up inference', 'Is applied at inference time as well'], 1, 'It is a regulariser; at inference dropout is disabled (with scaling handled by "inverted dropout" during training).'],
    ['Training Deep Nets', 'Adam differs from plain SGD mainly by:', ['Using no learning rate', 'Keeping per-parameter adaptive step sizes from running averages of gradients and squared gradients', 'Only working on CNNs', 'Computing second derivatives exactly'], 1, 'Adam = momentum (1st moment) + RMSProp-style scaling (2nd moment), with bias correction. AdamW decouples weight decay.'],
    ['Training Deep Nets', 'Batch Normalization normalises activations using statistics computed over:', ['The whole dataset at every step', 'The current mini-batch (running averages at inference)', 'A single example\'s features', 'The test set'], 1, 'BatchNorm uses batch mean/variance in training and running estimates at inference. Transformers typically use LayerNorm (per-token, over features).'],
    ['Architectures', 'The key advantage of convolutional layers over dense layers for images is:', ['They have more parameters', 'Weight sharing and local connectivity give translation equivariance with far fewer parameters', 'They do not need training', 'They work only on grayscale images'], 1, 'A small kernel slides over the image; the same weights detect a pattern anywhere.'],
    ['Architectures', 'Residual (skip) connections compute:', ['y = F(x)', 'y = F(x) + x', 'y = F(x) × x', 'y = x − F(x) only at the output'], 1, 'Adding the input lets gradients flow directly and makes very deep networks (ResNet, Transformers) trainable.'],
    ['Architectures', 'LSTMs were introduced to address which RNN problem?', ['Too many parameters', 'Difficulty learning long-range dependencies due to vanishing gradients', 'Inability to process images', 'Lack of GPUs'], 1, 'Gates (input, forget, output) and a cell state let information persist across many time steps.'],
    ['Transformers & Attention', 'In scaled dot-product attention, scores are divided by √d_k to:', ['Save memory', 'Keep dot products from growing large and saturating the softmax', 'Make attention causal', 'Normalise the output length'], 1, 'Attention(Q,K,V) = softmax(QKᵀ / √d_k) V. Large logits would make softmax nearly one-hot with tiny gradients.'],
    ['Transformers & Attention', 'Why do Transformers need positional encodings?', ['To reduce parameters', 'Self-attention is permutation-invariant, so it has no built-in notion of token order', 'To enable dropout', 'Only for image inputs'], 1, 'Sinusoidal, learned or rotary (RoPE) position information tells the model where each token is.'],
    ['Transformers & Attention', 'Multi-head attention helps because:', ['It removes the need for feed-forward layers', 'Different heads can attend to different relationships in parallel subspaces', 'It makes attention linear in sequence length', 'It is required for tokenisation'], 1, 'Each head has its own Q/K/V projections; outputs are concatenated and projected.'],
    ['Transformers & Attention', 'A decoder-only model like GPT uses a causal mask so that:', ['It can see future tokens', 'Each position attends only to itself and earlier positions', 'Attention is disabled', 'Padding tokens get more weight'], 1, 'Causal masking enables next-token prediction training on whole sequences in parallel.'],
    ['Transfer Learning', 'When fine-tuning a pretrained image model on a small dataset, a good first approach is to:', ['Train from scratch with a high learning rate', 'Freeze most early layers and train the head (then optionally unfreeze with a low LR)', 'Delete the pretrained weights', 'Use a batch size of 1'], 1, 'Early layers learn generic features; fine-tune gently to avoid destroying them (catastrophic forgetting).'],
    ['Loss Functions', 'For multi-class classification with softmax outputs, the standard loss is:', ['Mean squared error', 'Categorical cross-entropy', 'Hinge loss only', 'L1 loss'], 1, 'Cross-entropy = −log p(correct class). Binary cross-entropy is used with a sigmoid for binary/multi-label tasks.'],
    ['Generative Models', 'Diffusion models generate images by:', ['Sampling one pixel at a time', 'Learning to reverse a gradual noising process, denoising step by step', 'Using a discriminator only', 'Clustering training images'], 1, 'A network is trained to predict the noise added at each step; generation starts from noise and denoises iteratively.'],
  ];

  B.genai = [
    ['LLM Basics', 'LLMs like GPT or Llama are primarily pretrained to:', ['Classify sentiment', 'Predict the next token in large amounts of text', 'Translate only', 'Retrieve documents from a database'], 1, 'Self-supervised next-token prediction; instruction tuning and preference tuning (RLHF/DPO) come afterwards.'],
    ['LLM Basics', 'A token is best described as:', ['Always one word', 'A sub-word unit produced by the tokenizer (e.g., BPE)', 'One character', 'One sentence'], 1, 'Roughly ~4 characters of English text per token on average; other languages and code can use more tokens.'],
    ['LLM Basics', 'An LLM "hallucination" is:', ['A GPU memory error', 'Fluent output that is not grounded in facts or the provided sources', 'A tokenisation bug', 'A refusal to answer'], 1, 'Mitigate with retrieval (RAG), citations, constrained output, lower temperature, and evaluation.'],
    ['Prompt Engineering', 'Few-shot prompting means:', ['Training the model on a few examples', 'Including a few worked input→output examples in the prompt', 'Asking several models', 'Limiting the output to a few tokens'], 1, 'In-context learning — no weights change.'],
    ['Prompt Engineering', 'Which change most reliably gets machine-parseable output from an LLM app?', ['Asking politely', 'Using structured outputs / JSON mode or tool (function) calling with a schema, then validating', 'Raising the temperature', 'Using a longer system prompt only'], 1, 'Schemas + validation (and retry on failure) beat free-form instructions.'],
    ['Prompt Engineering', 'Prompt injection is when:', ['A prompt is too long', 'Untrusted content (a web page, document or user input) contains instructions that hijack the model', 'The model is fine-tuned', 'Two prompts are concatenated for speed'], 1, 'Treat retrieved/user content as data, restrict tools and permissions, and add output checks.'],
    ['RAG & Chunking', 'Retrieval-Augmented Generation (RAG) mainly helps an LLM to:', ['Train faster', 'Answer using up-to-date or private documents retrieved at query time', 'Reduce its parameter count', 'Generate images'], 1, 'Retrieve relevant chunks (vector/keyword/hybrid search), add them to the prompt, and ask the model to answer from them with citations.'],
    ['RAG & Chunking', 'Your RAG bot retrieves the wrong chunks for keyword-heavy queries like product codes. A good fix is:', ['Increase temperature', 'Hybrid search (BM25 keyword + vector) with reranking', 'Remove chunk overlap', 'Use a bigger LLM only'], 1, 'Dense embeddings can miss exact tokens; combining lexical and semantic retrieval, then reranking, improves recall and precision.'],
    ['RAG & Chunking', 'Chunk overlap in RAG is used to:', ['Reduce storage', 'Avoid cutting important context at chunk boundaries', 'Speed up embedding', 'Increase the context window'], 1, 'Overlap keeps sentences/ideas that straddle boundaries retrievable, at some storage cost.'],
    ['Embeddings & Vector DBs', 'Text embeddings are useful for semantic search because:', ['They compress text losslessly', 'Semantically similar texts map to nearby vectors (e.g., high cosine similarity)', 'They are always binary', 'They store the original words'], 1, 'Nearest-neighbour search over embeddings finds meaning-level matches.'],
    ['Embeddings & Vector DBs', 'Vector databases use Approximate Nearest Neighbour (ANN) indexes such as HNSW to:', ['Guarantee exact results', 'Trade a little recall for much faster search at scale', 'Train embeddings', 'Encrypt vectors'], 1, 'Exact search is O(N) per query; ANN graphs/IVF give sub-linear search.'],
    ['Fine-tuning', 'LoRA fine-tuning works by:', ['Updating all weights at a lower precision', 'Freezing base weights and training small low-rank adapter matrices', 'Pruning half the layers', 'Retraining the tokenizer'], 1, 'W + BA with low rank r drastically cuts trainable parameters and memory; QLoRA adds a 4-bit quantised base model.'],
    ['Fine-tuning', 'When should you prefer RAG over fine-tuning?', ['To teach a new output style or format', 'When answers must reflect frequently changing or private knowledge with sources', 'To make the model smaller', 'To reduce latency to zero'], 1, 'RAG injects knowledge at query time; fine-tuning is better for behaviour, style, format or narrow skills.'],
    ['Fine-tuning', 'RLHF / DPO are used to:', ['Pretrain on raw text', 'Align model outputs with human preferences', 'Compress models', 'Tokenise text'], 1, 'Preference data (chosen vs rejected responses) steers helpfulness and harmlessness.'],
    ['Agents & Tools', 'In LLM tool (function) calling, the model:', ['Executes code directly on your server', 'Returns a structured request (tool name + arguments) that your code executes and feeds back', 'Calls APIs over the internet by itself', 'Only works with images'], 1, 'Your application runs the tool, returns the result, and the model continues — the basis of agents.'],
    ['Agents & Tools', 'A common agent loop is:', ['Train → deploy → retrain', 'Reason → act (call a tool) → observe the result → repeat until done', 'Tokenise → embed → store', 'Prompt once and stop'], 1, 'ReAct-style loops; add step limits, tool permissions and evaluation to keep agents safe and reliable.'],
    ['Evaluation', 'The most practical way to evaluate a production LLM feature is:', ['Only perplexity on Wikipedia', 'A task-specific eval set with graded outputs (rules, reference answers or an LLM judge) run on every change', 'Asking one colleague', 'Checking token counts'], 1, 'Build golden datasets, automate grading, track regressions — like unit tests for prompts and models.'],
    ['Decoding & Sampling', 'Setting temperature to 0 (greedy decoding) generally makes outputs:', ['More creative', 'More deterministic and repeatable', 'Longer', 'Multilingual'], 1, 'Low temperature suits extraction/classification; higher values add diversity for brainstorming.'],
    ['Efficiency', 'Quantising an LLM from 16-bit to 4-bit weights mainly:', ['Increases accuracy', 'Cuts memory roughly 4× with a small quality loss, enabling cheaper/local inference', 'Increases the context window', 'Removes the need for a GPU in all cases'], 1, 'Weights take ~¼ of the space; methods like GPTQ/AWQ/GGUF keep quality loss small.'],
    ['Efficiency', 'The KV cache speeds up LLM generation by:', ['Caching previous answers to identical prompts', 'Storing attention keys/values of earlier tokens so each new token doesn\'t recompute them', 'Compressing the vocabulary', 'Skipping layers'], 1, 'It trades memory (grows with sequence length × layers) for much faster autoregressive decoding.'],
  ];

  B.mlops = [
    ['Deployment', 'Data drift means:', ['The model weights change on their own', 'The distribution of production input data shifts away from the training data', 'The server clock drifts', 'Labels are shuffled'], 1, 'Monitor feature distributions (e.g., PSI, KS tests) and performance; retrain when needed. Concept drift = the input→label relationship changes.'],
    ['Deployment', 'A shadow deployment of a new model:', ['Replaces the old model immediately', 'Receives real traffic and logs predictions without affecting users', 'Only runs offline on old data', 'Is a model with no monitoring'], 1, 'Compare with the live model safely, then roll out via canary or A/B testing.'],
    ['Deployment', 'Batch vs online (real-time) inference — which is TRUE?', ['Batch is always more accurate', 'Online serves low-latency predictions per request; batch precomputes predictions on a schedule', 'Online inference cannot use GPUs', 'Batch inference requires Kubernetes'], 1, 'Choose based on latency needs and freshness of features.'],
    ['Reproducibility', 'To reproduce a model exactly you should version:', ['Only the code', 'Code, data (or data snapshot), configs/hyperparameters, environment and random seeds', 'Only the final weights', 'Only the requirements.txt'], 1, 'Tools: Git, DVC/lakeFS, MLflow/W&B experiment tracking, Docker images.'],
    ['Reproducibility', 'MLflow or Weights & Biases are mainly used for:', ['Labelling images', 'Experiment tracking, model registry and comparing runs', 'Serving static websites', 'Tokenising text'], 1, 'They log params, metrics, artifacts and model versions.'],
    ['Infrastructure', 'Docker helps ML deployment by:', ['Training models faster', 'Packaging code and dependencies into a portable, reproducible container image', 'Replacing GPUs', 'Removing the need for monitoring'], 1, '"Works on my machine" → works everywhere the container runs; Kubernetes orchestrates many containers.'],
    ['Infrastructure', 'A feature store helps prevent:', ['GPU shortages', 'Training–serving skew by computing features the same way for training and inference', 'Tokenisation errors', 'Overfitting'], 1, 'Shared, versioned feature definitions for offline (training) and online (serving) use.'],
    ['Infrastructure', 'Which is a typical way to serve a PyTorch/scikit-learn model as an API?', ['Excel macros', 'Wrap it in FastAPI/Flask (or use a model server like TorchServe, Triton, BentoML) behind an HTTP endpoint', 'Email the pickle file', 'Put it in a CSV'], 1, 'Add input validation, batching, health checks, logging and autoscaling.'],
    ['Monitoring', 'In production you usually cannot compute accuracy immediately because:', ['Metrics are illegal', 'Ground-truth labels arrive late or never, so you monitor proxies (drift, confidence, business KPIs)', 'Models have no outputs', 'Logs are disabled'], 1, 'Set up delayed-label pipelines and proxy alerts.'],
    ['LLMOps', 'For an LLM app in production, which is MOST important to log (with privacy safeguards)?', ['Only server CPU usage', 'Prompts, retrieved context, outputs, latency, token usage/cost and user feedback', 'Only error codes', 'Nothing — LLMs are deterministic'], 1, 'These enable debugging, evaluation, cost control and improvement; redact personal data.'],
    ['LLMOps', 'Guardrails in an LLM application are:', ['GPU cooling systems', 'Checks on inputs/outputs (e.g., PII, policy, schema, jailbreak detection) around the model', 'A type of tokenizer', 'Fine-tuning datasets'], 1, 'Combine with least-privilege tools and human review for high-risk actions.'],
    ['Responsible AI', 'A loan model has much higher false-rejection rates for one demographic group. This is an issue of:', ['Latency', 'Fairness / bias', 'Overfitting to the test set', 'Quantisation'], 1, 'Measure metrics per group (e.g., equal opportunity), investigate data and features, and mitigate.'],
  ];

  if (typeof module !== 'undefined' && module.exports) module.exports = { mlfund: B.mlfund, dl: B.dl, genai: B.genai, mlops: B.mlops };
})(typeof window !== 'undefined' ? window : globalThis);
