/* General Awareness bank — static GK (stable facts only; use the AI generator for fresh practice). */
(function (root) {
  const B = (root.EP_BANK = root.EP_BANK || {});
  B.ga = [
    // Polity
    ['Polity', 'Which Article of the Indian Constitution abolishes untouchability?', ['Article 14', 'Article 17', 'Article 19', 'Article 21'], 1, 'Article 17 abolishes untouchability and forbids its practice in any form.'],
    ['Polity', 'The Right to Constitutional Remedies is provided under:', ['Article 32', 'Article 226', 'Article 356', 'Article 370'], 0, 'Article 32 — Dr. B.R. Ambedkar called it the "heart and soul" of the Constitution.'],
    ['Polity', 'Which amendment is known as the "Mini Constitution"?', ['24th', '42nd', '44th', '73rd'], 1, 'The 42nd Amendment (1976) made sweeping changes, adding "Socialist", "Secular" and "Integrity" to the Preamble.'],
    ['Polity', 'Fundamental Duties were added to the Constitution on the recommendation of:', ['Sarkaria Commission', 'Swaran Singh Committee', 'Balwant Rai Mehta Committee', 'Punchhi Commission'], 1, 'Swaran Singh Committee (1976); added as Article 51A by the 42nd Amendment.'],
    ['Polity', 'The concept of Directive Principles of State Policy was borrowed from the constitution of:', ['USA', 'Ireland', 'UK', 'Canada'], 1, 'DPSPs (Part IV) were inspired by the Irish Constitution.'],
    ['Polity', 'Who presides over a joint sitting of both Houses of Parliament?', ['President', 'Vice-President', 'Speaker of Lok Sabha', 'Prime Minister'], 2, 'Article 108 — the Speaker of the Lok Sabha presides over a joint sitting.'],
    ['Polity', 'Money Bills can be introduced only in:', ['Rajya Sabha', 'Lok Sabha', 'Either House', 'Joint sitting'], 1, 'Article 109/110 — a Money Bill can only be introduced in the Lok Sabha, on the President\'s recommendation.'],
    ['Polity', 'Which Article deals with the Finance Commission?', ['Article 280', 'Article 312', 'Article 324', 'Article 368'], 0, 'Article 280 — constituted every five years by the President.'],
    ['Polity', 'The Election Commission of India is established under:', ['Article 315', 'Article 324', 'Article 330', 'Article 352'], 1, 'Article 324 vests superintendence of elections in the Election Commission.'],
    ['Polity', 'Panchayati Raj institutions got constitutional status through the:', ['61st Amendment', '73rd Amendment', '74th Amendment', '86th Amendment'], 1, '73rd Amendment (1992) — Part IX; the 74th did the same for urban local bodies.'],
    ['Polity', 'The Right to Education (Article 21A) was inserted by the:', ['86th Amendment', '91st Amendment', '93rd Amendment', '97th Amendment'], 0, '86th Amendment Act, 2002 — free and compulsory education for children aged 6–14.'],
    ['Polity', 'Minimum age to become a member of the Rajya Sabha is:', ['25 years', '30 years', '35 years', '21 years'], 1, '30 years for Rajya Sabha; 25 for Lok Sabha; 35 for President.'],
    ['Polity', 'National Emergency can be declared under:', ['Article 352', 'Article 356', 'Article 360', 'Article 365'], 0, '352 — National Emergency; 356 — President\'s Rule; 360 — Financial Emergency.'],
    // History
    ['History', 'The Battle of Plassey was fought in:', ['1757', '1764', '1857', '1761'], 0, '1757 — Robert Clive defeated Siraj-ud-Daulah.'],
    ['History', 'Who founded the Indian National Congress in 1885?', ['Dadabhai Naoroji', 'A.O. Hume', 'Bal Gangadhar Tilak', 'W.C. Bonnerjee'], 1, 'Allan Octavian Hume; W.C. Bonnerjee presided over the first session in Bombay.'],
    ['History', 'The Jallianwala Bagh massacre took place in:', ['1915', '1919', '1920', '1922'], 1, '13 April 1919, Amritsar, under General Dyer.'],
    ['History', 'The Dandi March (Salt Satyagraha) began in:', ['1920', '1928', '1930', '1942'], 2, 'Started 12 March 1930 from Sabarmati Ashram.'],
    ['History', 'The Quit India Movement was launched in:', ['1940', '1942', '1945', '1946'], 1, '8 August 1942, Bombay session — "Do or Die".'],
    ['History', 'Who was the founder of the Maurya Empire?', ['Ashoka', 'Bindusara', 'Chandragupta Maurya', 'Bimbisara'], 2, 'Chandragupta Maurya, with the guidance of Chanakya (Kautilya).'],
    ['History', 'The Buddhist council held at Pataliputra was convened by:', ['Ajatashatru', 'Kalasoka', 'Ashoka', 'Kanishka'], 2, 'The Third Buddhist Council (c. 250 BCE) under Ashoka, presided by Moggaliputta Tissa.'],
    ['History', 'The First Battle of Panipat (1526) was fought between Babur and:', ['Rana Sanga', 'Ibrahim Lodi', 'Hemu', 'Sher Shah Suri'], 1, 'Babur defeated Ibrahim Lodi and founded the Mughal Empire.'],
    ['History', 'Who wrote "Gitanjali"?', ['Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Munshi Premchand'], 1, 'Tagore received the Nobel Prize in Literature in 1913.'],
    ['History', 'The Permanent Settlement of Bengal (1793) was introduced by:', ['Lord Wellesley', 'Lord Cornwallis', 'Lord Dalhousie', 'Warren Hastings'], 1, 'Lord Cornwallis — fixed land revenue with zamindars.'],
    ['History', 'The Doctrine of Lapse is associated with:', ['Lord Dalhousie', 'Lord Curzon', 'Lord Ripon', 'Lord Canning'], 0, 'Lord Dalhousie annexed Satara, Jhansi, Nagpur etc. under it.'],
    // Geography
    ['Geography', 'Which is the longest river flowing entirely within India?', ['Godavari', 'Ganga', 'Krishna', 'Narmada'], 1, 'The Ganga. Among peninsular rivers, the Godavari is the longest ("Dakshin Ganga").'],
    ['Geography', 'The Tropic of Cancer does NOT pass through which state?', ['Rajasthan', 'Odisha', 'Tripura', 'Jharkhand'], 1, 'It passes through Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, Mizoram — not Odisha.'],
    ['Geography', 'Nanda Devi peak is located in which state?', ['Himachal Pradesh', 'Uttarakhand', 'Sikkim', 'Jammu & Kashmir'], 1, 'Nanda Devi (7,816 m) is in Uttarakhand; the Nanda Devi and Valley of Flowers National Parks are a UNESCO World Heritage Site.'],
    ['Geography', 'Black soil is most suitable for growing:', ['Rice', 'Tea', 'Cotton', 'Wheat'], 2, 'Black (regur) soil retains moisture — ideal for cotton.'],
    ['Geography', 'Which strait separates India and Sri Lanka?', ['Malacca Strait', 'Palk Strait', 'Bering Strait', 'Strait of Hormuz'], 1, 'Palk Strait lies between Tamil Nadu and northern Sri Lanka.'],
    ['Geography', 'The Western Ghats are also known as:', ['Sahyadri', 'Aravalli', 'Satpura', 'Vindhya'], 0, 'Sahyadri.'],
    ['Geography', 'Which is the largest state of India by area?', ['Madhya Pradesh', 'Maharashtra', 'Rajasthan', 'Uttar Pradesh'], 2, 'Rajasthan.'],
    ['Geography', 'Loktak Lake is located in:', ['Assam', 'Manipur', 'Meghalaya', 'Sikkim'], 1, 'Manipur — famous for floating phumdis and Keibul Lamjao National Park.'],
    ['Geography', 'Kaziranga National Park is famous for:', ['Asiatic lion', 'One-horned rhinoceros', 'Snow leopard', 'Bengal tiger only'], 1, 'Assam — home to most of the world\'s one-horned rhinoceros.'],
    ['Geography', 'Which planet is known as the "Red Planet"?', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 1, 'Mars — iron oxide on its surface.'],
    // Science
    ['Science', 'The SI unit of force is:', ['Joule', 'Newton', 'Pascal', 'Watt'], 1, 'Newton (kg·m/s²).'],
    ['Science', 'Which vitamin deficiency causes scurvy?', ['Vitamin A', 'Vitamin B1', 'Vitamin C', 'Vitamin D'], 2, 'Vitamin C (ascorbic acid).'],
    ['Science', 'The powerhouse of the cell is:', ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi body'], 2, 'Mitochondria produce ATP.'],
    ['Science', 'Which gas is most abundant in Earth\'s atmosphere?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], 1, 'Nitrogen ≈ 78%, oxygen ≈ 21%.'],
    ['Science', 'The chemical formula of common salt is:', ['NaCl', 'KCl', 'Na2CO3', 'NaHCO3'], 0, 'Sodium chloride. NaHCO3 is baking soda; Na2CO3 is washing soda.'],
    ['Science', 'pH of pure water at 25°C is:', ['0', '7', '14', '1'], 1, 'Neutral = 7.'],
    ['Science', 'Which blood group is known as the universal donor?', ['A', 'B', 'AB', 'O negative'], 3, 'O negative; AB positive is the universal recipient.'],
    ['Science', 'Sound cannot travel through:', ['Water', 'Steel', 'Vacuum', 'Air'], 2, 'Sound needs a material medium.'],
    ['Science', 'The hardest natural substance is:', ['Iron', 'Diamond', 'Graphite', 'Quartz'], 1, 'Diamond — an allotrope of carbon.'],
    ['Science', 'Insulin is secreted by the:', ['Liver', 'Pancreas', 'Kidney', 'Thyroid'], 1, 'Beta cells of the islets of Langerhans in the pancreas.'],
    ['Computer', 'Which of these is NOT an input device?', ['Keyboard', 'Mouse', 'Scanner', 'Monitor'], 3, 'A monitor is an output device.'],
    ['Computer', '1 kilobyte (KB) is equal to:', ['1000 bits', '1024 bytes', '1024 bits', '1000 megabytes'], 1, '1 KB = 1024 bytes (binary convention used in exams).'],
    ['Computer', 'The shortcut Ctrl + Z is used to:', ['Redo', 'Undo', 'Cut', 'Save'], 1, 'Undo; Ctrl + Y is Redo.'],
    // Economy & banking (also RBI GA)
    ['Banking Awareness', 'The Reserve Bank of India was established in:', ['1935', '1947', '1949', '1969'], 0, '1 April 1935 under the RBI Act, 1934; nationalised on 1 January 1949.'],
    ['Banking Awareness', 'The RBI was established on the recommendation of the:', ['Hilton Young Commission', 'Narasimham Committee', 'Rangarajan Committee', 'Chakravarty Committee'], 0, 'Royal Commission on Indian Currency and Finance (Hilton Young Commission), 1926.'],
    ['Banking Awareness', 'Which section of the RBI Act gives the RBI the sole right to issue banknotes?', ['Section 17', 'Section 22', 'Section 24', 'Section 42'], 1, 'Section 22. (₹1 notes are issued by the Government of India, Ministry of Finance.)'],
    ['Banking Awareness', 'The rate at which the RBI lends short-term funds to commercial banks against government securities is:', ['Bank Rate', 'Repo Rate', 'Reverse Repo Rate', 'MSF Rate'], 1, 'Repo rate — the policy rate of the RBI\'s LAF.'],
    ['Banking Awareness', 'CRR (Cash Reserve Ratio) is maintained by banks with:', ['Themselves as cash', 'The RBI', 'SBI', 'NABARD'], 1, 'CRR is kept as cash balance with the RBI; SLR is kept with the bank itself in liquid assets.'],
    ['Banking Awareness', 'The Monetary Policy Committee (MPC) of the RBI has how many members?', ['4', '5', '6', '7'], 2, 'Six — three from the RBI (Governor chairs) and three appointed by the Government.'],
    ['Banking Awareness', 'Fourteen major commercial banks were nationalised in:', ['1955', '1969', '1980', '1991'], 1, '19 July 1969; six more were nationalised in 1980.'],
    ['Banking Awareness', 'NABARD was established in:', ['1975', '1982', '1990', '1964'], 1, '12 July 1982, on the recommendation of the Shivaraman (CRAFICARD) Committee.'],
    ['Banking Awareness', 'SIDBI is the principal financial institution for:', ['Agriculture', 'MSME sector', 'Housing', 'Exports'], 1, 'Small Industries Development Bank of India (1990), HQ Lucknow.'],
    ['Banking Awareness', 'Minimum amount for an RTGS transaction is:', ['₹1 lakh', '₹2 lakh', '₹5 lakh', 'No minimum'], 1, 'RTGS is meant for large-value transfers; minimum ₹2 lakh.'],
    ['Banking Awareness', 'UPI was developed by:', ['RBI', 'NPCI', 'SBI', 'IDRBT'], 1, 'National Payments Corporation of India launched UPI in 2016.'],
    ['Banking Awareness', 'The Deposit Insurance and Credit Guarantee Corporation (DICGC) insures deposits up to:', ['₹1 lakh', '₹2 lakh', '₹5 lakh', '₹10 lakh'], 2, '₹5 lakh per depositor per bank (raised from ₹1 lakh in 2020).'],
    ['Banking Awareness', 'The "lender of last resort" in India is:', ['SBI', 'Ministry of Finance', 'RBI', 'NABARD'], 2, 'The central bank acts as lender of last resort to banks.'],
    ['Banking Awareness', 'Basel norms relate to:', ['Capital adequacy of banks', 'Foreign trade', 'Taxation', 'Insurance'], 0, 'Basel Committee on Banking Supervision (BIS, Basel) sets capital, leverage and liquidity standards.'],
    ['Banking Awareness', 'Headquarters of the Asian Development Bank is at:', ['Tokyo', 'Manila', 'Beijing', 'Singapore'], 1, 'Manila, Philippines.'],
    ['Banking Awareness', 'The New Development Bank was set up by:', ['SAARC', 'BRICS', 'G20', 'ASEAN'], 1, 'BRICS nations; HQ Shanghai.'],
    ['Banking Awareness', 'SARFAESI Act was enacted in:', ['1999', '2002', '2016', '1993'], 1, 'Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act, 2002.'],
    ['Banking Awareness', 'The Insolvency and Bankruptcy Code was enacted in:', ['2014', '2016', '2018', '2019'], 1, 'IBC, 2016.'],
    ['Banking Awareness', 'A cheque is valid for how long from the date of issue?', ['1 month', '3 months', '6 months', '1 year'], 1, 'Three months (RBI, since 1 April 2012).'],
    ['Banking Awareness', 'A rupee account maintained by a foreign bank with a bank in India is called (from the Indian bank\'s point of view):', ['Nostro account', 'Vostro account', 'Loro account', 'Escrow account'], 1, 'Vostro ("yours") — the foreign bank\'s account held with us. Nostro ("ours") is an Indian bank\'s account held abroad in foreign currency.'],
    ['Banking Awareness', 'Priority sector lending target for domestic scheduled commercial banks is what percentage of ANBC?', ['18%', '25%', '40%', '50%'], 2, '40% of Adjusted Net Bank Credit (or credit-equivalent of off-balance sheet exposure, whichever is higher).'],
    ['Economy', 'GST was implemented in India from:', ['1 April 2017', '1 July 2017', '1 January 2018', '1 July 2016'], 1, '1 July 2017, via the 101st Constitutional Amendment Act, 2016.'],
    ['Economy', 'NITI Aayog replaced the Planning Commission on:', ['1 January 2015', '15 August 2014', '26 January 2015', '1 April 2015'], 0, 'NITI Aayog was set up on 1 January 2015; the PM is its chairperson.'],
    ['Economy', 'The fiscal year in India runs from:', ['January–December', 'April–March', 'July–June', 'October–September'], 1, '1 April to 31 March.'],
    ['Economy', 'SEBI was given statutory powers in:', ['1988', '1992', '1995', '2000'], 1, 'Set up in 1988; became statutory under the SEBI Act, 1992.'],
    ['Economy', 'Which organisation publishes the World Development Report?', ['IMF', 'World Bank', 'WTO', 'UNDP'], 1, 'The World Bank. The IMF publishes the World Economic Outlook; UNDP the Human Development Report.'],
    ['Sports & Culture', 'The Durand Cup is associated with:', ['Cricket', 'Hockey', 'Football', 'Tennis'], 2, 'Football — one of the oldest club tournaments in the world (1888).'],
    ['Sports & Culture', 'Kathakali is a classical dance form of:', ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], 1, 'Kerala.'],
    ['Sports & Culture', 'Bihu is a festival of:', ['Assam', 'Odisha', 'Punjab', 'Bihar'], 0, 'Assam.'],
    ['Sports & Culture', 'How many players are there on a side in a hockey match on the field?', ['9', '10', '11', '12'], 2, '11 including the goalkeeper.'],
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = B.ga;
})(typeof window !== 'undefined' ? window : globalThis);
