/* Hand-written reasoning questions for topics that are unsafe to auto-generate. */
(function (root) {
  const B = (root.EP_BANK = root.EP_BANK || {});
  B.reasoning = [
    ['Syllogism', 'Statements: All cats are dogs. All dogs are birds.\nConclusions: I. All cats are birds. II. Some birds are cats.', ['Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows'], 2, 'Cats ⊂ dogs ⊂ birds ⇒ all cats are birds (I). Hence some birds are cats (II, conversion).'],
    ['Syllogism', 'Statements: Some pens are books. All books are tables.\nConclusions: I. Some pens are tables. II. All tables are pens.', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 0, 'The pens that are books are also tables ⇒ I follows. II is not definite.'],
    ['Syllogism', 'Statements: No man is a tree. All trees are green.\nConclusions: I. No man is green. II. Some green things are not men.', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 1, 'Trees are green and no tree is a man ⇒ those green things (trees) are not men (II). I is not definite.'],
    ['Syllogism', 'Statements: Some rings are gold. Some gold is silver.\nConclusions: I. Some rings are silver. II. No ring is silver.', ['Only I follows', 'Only II follows', 'Either I or II follows', 'Neither follows'], 2, 'No definite link between rings and silver, but I and II form a complementary pair (some / no) about the same terms ⇒ either I or II.'],
    ['Syllogism', 'Statements: All roses are flowers. No flower is a leaf.\nConclusions: I. No rose is a leaf. II. Some leaves are roses.', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 0, 'Roses ⊂ flowers, flowers ∩ leaves = ∅ ⇒ no rose is a leaf. II contradicts I.'],
    ['Syllogism', 'Statements: Only a few doctors are engineers. All engineers are teachers.\nConclusions: I. Some doctors are teachers. II. All doctors are engineers.', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 0, '"Only a few A are B" = some A are B and some A are not B. So some doctors are teachers (I); II is false.'],
    ['Blood Relations', 'Pointing to a boy, Neha said, "His mother is the only daughter of my mother." How is the boy related to Neha?', ['Brother', 'Nephew', 'Son', 'Cousin'], 2, 'The only daughter of Neha\'s mother is Neha herself. So the boy\'s mother is Neha ⇒ he is her son.'],
    ['Blood Relations', 'A is the brother of B. B is the sister of C. C is the son of D. How is A related to D?', ['Son', 'Daughter', 'Nephew', 'Brother'], 0, 'A, B, C are siblings, all children of D; A is male ⇒ son.'],
    ['Blood Relations', 'P is the father of Q. Q is the mother of R. S is the brother of P. How is S related to R?', ['Uncle', 'Grandfather', 'Great uncle (grandfather\'s brother)', 'Cousin'], 2, 'P is R\'s maternal grandfather; S is P\'s brother ⇒ R\'s grand-uncle.'],
    ['Blood Relations', 'Introducing a woman, Rohan said, "She is the only daughter of my mother\'s father." How is the woman related to Rohan?', ['Sister', 'Mother', 'Aunt', 'Grandmother'], 1, 'The only daughter of Rohan\'s mother\'s father is Rohan\'s mother herself.'],
    ['Blood Relations', 'M is the wife of N. N is the son of O. O has only one son. P is the daughter of M. How is P related to O?', ['Daughter', 'Granddaughter', 'Niece', 'Daughter-in-law'], 1, 'N is O\'s son and P is N\'s daughter (via M) ⇒ granddaughter.'],
    ['Seating Arrangement', 'Five friends A, B, C, D and E sit in a row facing north. C is in the middle. A is to the immediate left of C. E is at the extreme right. B is not at an end. Who is at the extreme left?', ['A', 'B', 'D', 'E'], 2, 'Positions 1–5 (left→right): C = 3, A = 2, E = 5. B is not at an end ⇒ B = 4, so D = 1 (extreme left).'],
    ['Seating Arrangement', 'Six people A, B, C, D, E and F sit around a circular table at equal distances. A sits opposite D. B sits next to A. E sits opposite B. C does not sit next to A. Who sits opposite C?', ['A', 'B', 'E', 'F'], 3, 'Number seats 1–6: A = 1, D = 4. B next to A: seat 2 (seat 6 is a mirror image). E opposite B = 5. Seats 3 and 6 remain; seat 6 is next to A, so C = 3 and F = 6. Seat 3 is opposite seat 6 ⇒ F.'],
    ['Seating Arrangement', 'In a row of 5 people facing south, X is second from the left end. Y is to the immediate right of X. Who is to the immediate left of Y?', ['X', 'Cannot be determined', 'Z', 'Nobody'], 0, 'Directions (facing south) do not matter here: "immediate right of X" means Y is adjacent to X, so X is on Y\'s immediate left.'],
    ['Statement & Conclusion', 'Statement: "Regular exercise keeps you fit." — Advertisement of a gym.\nConclusions: I. People want to be fit. II. Exercise is harmful.', ['Only I follows', 'Only II follows', 'Both follow', 'Neither follows'], 0, 'The ad assumes people value fitness (I). II contradicts the statement.'],
    ['Venn Diagram', 'Which diagram best represents: Mammals, Whales, Fish?', ['Whales inside Mammals; Fish separate', 'All three separate', 'Whales inside Fish', 'All three overlapping'], 0, 'Whales are mammals, not fish; fish and mammals are disjoint.'],
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = B.reasoning;
})(typeof window !== 'undefined' ? window : globalThis);
